export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
export const ADD_USER_INFORMATION = "ADD_USER_INFORMATION";
export const ADD_REPOSITORIES_INFORMATION = "ADD_REPOSITORIES_INFORMATION";
export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS";
